IB/mlx4: Potential buffer overflow in _mlx4_set_path()
Smatch complains about this code:

    drivers/infiniband/hw/mlx4/mlx4_ib_qp.c:1827 _mlx4_set_path()
    error: buffer overflow 'dev->dev->caps.gid_table_len' 3 <= 255

The mlx4_ib_gid_index_to_real_index() does check that "port" is within
bounds, but we don't check the return value for errors.  It seems simple
enough to add a check for that.

Obtained from:	Linux commit 54a6d63f14bdb4e899bbb4128d32717074d13862