RDMA/core: Reduce poll batch for direct cq polling
Fix warning limit for kernel stack consumption:

drivers/infiniband/core/ib_cq.c: In function 'ib_process_cq_direct':
drivers/infiniband/core/ib_cq.c:78:1: error: the frame size of 1032 bytes
is larger than 1024 bytes [-Werror=frame-larger-than=]

Using smaller ib_wc array on the stack brings us comfortably below that
limit again.

Obtained from:	Linux commit d3b9e8ad425cfd5b9116732e057f1b48e4d3bcb8